board:
    states:
        - ruhr: |
            -------
            | [U] |
            |ruhr |
            -------
        - kiel: |
            -----------------
            |       [U]     |
            |       kiel    |
            -----------------
        - berlin: |
            -----------
            |   [U]   |
            |  berlin |
            -----------
        - prussia: |
            -------
            | [U] |
            |prssa|
            -------
        - munich: |
            ------------------------------
            |  munich   [U]              |
            ------------------------------
        - silesia: |
            ------------
            |silesia[U]|
            ------------
    board_drawing:
        - layer0:
            - ruhr
            - kiel
            - berlin
            - prussia
        - layer1:
            - munich
            - silesia
    board_matrix:
        - ruhr:
            - kiel
            - munich
        - kiel:
            - ruhr
            - munich
            - berlin
        - berlin:
            - kiel
            - munich
            - silesia
            - prussia
        - prussia:
            - berlin
            - silesia
        - munich:
            - ruhr
            - kiel
            - berlin
            - silesia
        - silesia:
            - munich
            - prussia
            - berlin
